### ISSUE TITLE
Extracting mp_masterchief in any configuration will cause crash to desktop.

### ISSUE THREAD

**Issue by KuroxLemming** [Gravemind2401/Reclaimer#27]
The title says it pretty well but will go into a little bit more detail.

Tried extracting the model from render_model folder with any halo 3 map and it will just CTD every time.

Steps I have tried

- Reinstalling Recalimer
- Different Maps
- Only extracting one body part at a time and stitching it together later.
- Extracting the giant clump all together and still CTD.
- Running As admin both with and without same effect.

I have managed to extract other models the same way in the past with 0 issues, but there seems to be an odd bug causing it to crash.

if there are any logs I could provide, please let me know and I will send them over.

Any help on this issue would be greatly appreciated.

**Comment by Godlike938** [comment]
Hi Kurox,

I think I might of had found a temporary solution to this problem. I wont bore you with the details but it might be do to how heavy the share.map is. what I found was that if you increase the worker count it will spread the load of extracting the file.

Tools>Settings>Batch Extractor>Batch Worker Count (mine was at 1) then bump it up to 10 or what ever highest number you can.

i was having the same problem word for word and this seem to help, i does look like it freeze's but it does come back and it doesn't crash and not give a reason for it.

i hope this can help for the time being until gravemind finds a solution

**Comment by KuroxLemming** [comment]
> Hi Kurox,
> 
> I think I might of had found a temporary solution to this problem. I wont bore you with the details but it might be do to how heavy the share.map is. what I found was that if you increase the worker count it will spread the load of extracting the file.
> 
> Tools>Settings>Batch Extractor>Batch Worker Count (mine was at 1) then bump it up to 10 or what ever highest number you can.
> 
> i was having the same problem word for word and this seem to help, i does look like it freeze's but it does come back and it doesn't crash and not give a reason for it.
> 
> i hope this can help for the time being until gravemind finds a solution

Gave this a shot trying different worker settings and it still just crashes to desktop.

I'm only trying to extract any part of the raven armor either as a whole or individual parts it just crashes.

I can extract the gear items without any problems and any other models just MP_masterchief nope gone doesn't like it at all.

**Comment by Godlike938** [comment]
Hey Kurox,

sorry for a long time to reply to this. 

so after a little more working i notice that i still have the same problem but Batch extraction still works and with the workers max out it seems like it doesn't crash, from what have found. so it might be a little bit of leg work to get the armor set you are looking for but that might be the only way that would seem to work for right now if you are trying to extracting in COLLADA.

i also did some other styles to see if that might help and AMF is able to not cause the crash and i believe OBJ just the OBJ and not the one with the materials attached.

Now with the Batch extraction. if you are needing the Bitmaps for it, i was able to do so just the normal extract bitmap selected. if that doesn't work you can do so by right clicking and extracting there as well but that might take a little longer and a little more leg work sifting through the bitmaps that are needed.

hopefully this helps and if i find anything more i will for sure make a note here.

**Comment by KuroxLemming** [comment]
> 

Been testing it a bit here and there to see what I can do to try and get the models out and tried obj with and without materials attached, tried a load of different model files and nope MP_masterchief still just crashes.
Can extract a lot of other things but not that at all even tried a load of different maps. 
Have you had any luck getting any of the armor pieces out?

**Comment by Godlike938** [comment]
so far i was able to get full MP but not able to select what i want so what i can do is upload what i got to a google drive and send that and hopefully that will work. you will have to select and delete the other amours but they will all be there in a clump and i will try to get the bitmaps in a folder for ya as well and leave it in your hands. if that works for ya?

**Comment by Godlike938** [comment]
alright, so this was what i was able to get and i cleaned the file up a little bit, if i had missed anything please let me know an i will see what i can do. https://drive.google.com/drive/folders/1ng5k1gsGGd0VWQDDdHZx7sEn2ybnyECf?usp=sharing

**Comment by KuroxLemming** [comment]
> so far i was able to get full MP but not able to select what i want so what i can do is upload what i got to a google drive and send that and hopefully that will work. you will have to select and delete the other amours but they will all be there in a clump and i will try to get the bitmaps in a folder for ya as well and leave it in your hands. if that works for ya?

Thanks for the files looks like the most recent update has broken it so will need a update now anyway.

**Comment by Gravemind2401** [comment]
This is most likely due to the app running out of memory due to the huge amount of pieces that the mp_masterchief model has. From the `View` menu using the `App Directory` or `AppData Directory` options there may be a crash text file in one of those folders with details of the last crash.

The least resource intensive way you can extract the model is by right-clicking on the tag name and selecting `Extract`, however this won't allow you to filter out the parts you want. If you open it in the model viewer first it will consume a large amount of memory for rendering leaving space left over for the extraction process to use.

**Comment by KuroxLemming** [comment]
[crash.txt](https://github.com/Gravemind2401/Reclaimer/files/9034326/crash.txt)
Here is my crashlog hope it helps you get to the root of the problem.

**Comment by Gravemind2401** [comment]
Based on the log it does look to be a memory issue. The error is coming from within Assimp; a third-party library Reclaimer uses for exporting obj and collada files. Obj and collada are also text-based formats, making them particularly memory intensive for models with such huge poly counts. Assimp also seems to have trouble exporting to collada in general when it comes to high poly counts.

If you are using obj or collada, see if you can export the model successfully as AMF. Reclaimer handles AMF directly rather than using Assimp, and since its a binary format it will be much smaller and require less memory.

**Comment by KuroxLemming** [comment]
I'm trying to extract from the MCC as well with the recent update. I can't test new settings but will happily test when you have chance to update as much as you need.

**Comment by Gravemind2401** [comment]
I don't know why Assimp seems to have issues with certain models in collada format when it is able to export them, but the memory related crashes are more of an issue with the collada and obj formats themself than with Assimp. Since those formats are text-based they take up significant amounts of space when it comes to models with high poly counts.
The only way to allow Reclaimer to use more memory would be to build it as a 64bit application, however that's not currently an option because Halo4 Xbox support relies on a 32bit-only third party library.
