### ISSUE TITLE
Wrong version on github

### ISSUE THREAD

**Issue by NuggetWarmer** [Gravemind2401/Reclaimer#42]
![image](https://user-images.githubusercontent.com/15763488/236095448-80ba3a3f-1517-4720-b447-18ce44772dd6.png)
I can't update because the version attached to the update post is not correct.

**Comment by ImpulseTM** [comment]
This has been an issue for over a month now and still nothing has been said about it.

Furthermore; Halo 2 MCC .map from h2_maps_win64_dx11 cannot be loaded any longer, previous versions were able to load these maps and installing older versions does not allow it to load said maps. 
Despite the map being un-updated since 2022 reclaimer still says its an unsupported version
(I have confirmed in the past that reclaimer is able to open and extract halo 2 files)

A fix would be appreciated.

**Comment by NuggetWarmer** [comment]
I have, for the moment, been using the xbox versions of the maps as they still seem to work, but yes this needs to be fixed, please.

**Comment by Gravemind2401** [comment]
@NuggetWarmer 833 was meant to fix issues with the MSI file from 832. The installer file did get updated but evidently the build number didn't change as I expected it to. I have edited the version description to prevent it from trying to update infinitely.

@ImpulseTM Nothing has been said because this thread is the first time anyone has raised it with me. Regarding Halo 2; the MCC Halo 2 campaign files have never been supported - only the H2A multiplayer maps and the original Xbox maps are supported. Halo 2 Vista maps can also be _opened_ but nothing can actually be extracted.

**Comment by NuggetWarmer** [comment]
I was supposed to what? You got the wrong guy Ace

**Comment by NuggetWarmer** [comment]
Oh thanks for the fix
